### PR TITLE
Solves TT-1015. Updated AWS-SES driver tu use official SDK

### PR DESCRIPTION
**Pull request by padiazg**
Updated the AWS-SES driver to use the official SDK.

This driver expects to receive these parameters:
```
  "settings": {
    "Region":          "",
    "AccessKeyId":     "",
    "SecretAccessKey": ""
  }
```

If `Region` is missing, but `Endpoint` is present the driver will try to extract the region from there

### CODE REVIEW

**Comment by padiazg** [comment]
After this update, we need to update the documentation too:
https://tyk.io/docs/tyk-configuration-reference/outbound-email-configuration/#amazon-ses

**Comment by marksou** [comment]
@padiazg can you raise an issue in the docs board to update with the changes.

**Review by matiasinsaurralde — APPROVED** [review]
Looks good!

**Review by excieve — APPROVED** [review]
LGTM, thanks!

Do I read it right that it also seems to address the env var configuration issue for AWS SES backend specifically by using the new `Region` option, which wouldn't include any colons to cause issues with `envconfig`?

We need to address the env var configuration for the other backends too (like the SMTP backend, which uses a colon for the port specification), but perhaps in the other tickets.

**Comment by padiazg** [comment]
The colon issue can be solved if we use a `Port` parameter, and then we figure out if it's plain SMTP or SMTP over SSL. Also, we can use another parameter, let's say `SSL` to override this in case the mail server uses ports different from 25, 465 or 587

**Comment by padiazg** [comment]
> @padiazg can you raise an issue in the docs board to update with the changes.

I'll do this once some of the applications used this driver will be published, and are using this new version. Until then, this new functionality doesn't affect the actual behaviour.

**Pull request merged**
